import random
import logging
from typing import List, Dict, Any

from problem_loader import ProblemData
from mutant_generator import generate_mutants_with_llm
from code_executor import evaluate_solution


def create_code_pairs(
    problem: ProblemData,
    num_mutants: int,
    max_pairs: int,
) -> List[Dict[str, Any]]:
    """
    Orchestrate the full pipeline: generate mutants, evaluate them, and build
    preference pairs.

    Args:
        problem: ProblemData object with problem data.
        num_mutants: Number of mutants to be generated by the LLM.
        max_pairs: Maximum number of pairs to be saved for this problem.

    Returns:
        A list of dictionaries, where each dictionary is a preference pair.
    """
    logging.info(f"Starting pair creation for problem: '{problem.problem_id}'")

    # 1. Verify the reference solution to ensure it is a correct baseline.
    original_result = evaluate_solution(problem.reference_solution, problem.tests)
    if not original_result.passed:
        logging.warning(
            f"The reference solution for '{problem.problem_id}' FAILED the tests. "
            "No pairs will be generated for this problem."
        )
        return []

    correct_solution = problem.reference_solution
    logging.info("Reference solution successfully verified.")

    # 2. Generate candidate incorrect answers using the LLM.
    candidate_mutants = generate_mutants_with_llm(problem, num_mutants)
    if not candidate_mutants:
        logging.warning(
            f"No mutants were generated for '{problem.problem_id}'. No pairs will be generated."
        )
        return []

    # 3. Evaluate each mutant and keep only those that fail the tests.
    incorrect_solutions = []
    for i, mutant in enumerate(candidate_mutants):
        logging.info(f"Evaluating mutant {i + 1}/{len(candidate_mutants)}...")
        mutant_result = evaluate_solution(mutant, problem.tests)
        if not mutant_result.passed:
            incorrect_solutions.append(mutant)
        else:
            logging.warning(
                f"Equivalent mutant (passed all tests) found and discarded for '{problem.problem_id}'."
            )

    if not incorrect_solutions:
        logging.warning(
            "None of the generated mutants failed the tests. No pairs will be generated."
        )
        return []

    logging.info(
        f"Found {len(incorrect_solutions)} valid incorrect solutions after evaluation."
    )

    # 4. Build the final pairs.
    created_pairs = []
    for incorrect_solution in incorrect_solutions:
        # Randomize the (A/B) order to avoid bias during future training.
        if random.random() < 0.5:
            response_A = correct_solution
            response_B = incorrect_solution
            label = "A>B"
        else:
            response_A = incorrect_solution
            response_B = correct_solution
            label = "B>A"

        pair = {
            "problem_id": problem.problem_id,
            "prompt": problem.statement,
            "response_A": response_A,
            "response_B": response_B,
            "label": label,
        }
        created_pairs.append(pair)

    # 5. Shuffle and limit the number of pairs as requested.
    random.shuffle(created_pairs)
    final_pairs = created_pairs[:max_pairs]

    logging.info(
        f"Created and selected {len(final_pairs)} preference pairs for '{problem.problem_id}'."
    )
    return final_pairs





